//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewComercio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articles", Namespace="http://schemas.datacontract.org/2004/07/WSComercio")]
    [System.SerializableAttribute()]
    public partial class Articles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddWSArticle", ReplyAction="http://tempuri.org/IService1/AddWSArticleResponse")]
        int AddWSArticle(string Description, double Price, int Stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddWSArticle", ReplyAction="http://tempuri.org/IService1/AddWSArticleResponse")]
        System.Threading.Tasks.Task<int> AddWSArticleAsync(string Description, double Price, int Stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaWSArticle", ReplyAction="http://tempuri.org/IService1/EditaWSArticleResponse")]
        void EditaWSArticle(int Id, string Description, double Price, int Stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaWSArticle", ReplyAction="http://tempuri.org/IService1/EditaWSArticleResponse")]
        System.Threading.Tasks.Task EditaWSArticleAsync(int Id, string Description, double Price, int Stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowWSArticles", ReplyAction="http://tempuri.org/IService1/ShowWSArticlesResponse")]
        ViewComercio.ServiceReference1.Articles[] ShowWSArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowWSArticles", ReplyAction="http://tempuri.org/IService1/ShowWSArticlesResponse")]
        System.Threading.Tasks.Task<ViewComercio.ServiceReference1.Articles[]> ShowWSArticlesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ViewComercio.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ViewComercio.ServiceReference1.IService1>, ViewComercio.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddWSArticle(string Description, double Price, int Stock) {
            return base.Channel.AddWSArticle(Description, Price, Stock);
        }
        
        public System.Threading.Tasks.Task<int> AddWSArticleAsync(string Description, double Price, int Stock) {
            return base.Channel.AddWSArticleAsync(Description, Price, Stock);
        }
        
        public void EditaWSArticle(int Id, string Description, double Price, int Stock) {
            base.Channel.EditaWSArticle(Id, Description, Price, Stock);
        }
        
        public System.Threading.Tasks.Task EditaWSArticleAsync(int Id, string Description, double Price, int Stock) {
            return base.Channel.EditaWSArticleAsync(Id, Description, Price, Stock);
        }
        
        public ViewComercio.ServiceReference1.Articles[] ShowWSArticles() {
            return base.Channel.ShowWSArticles();
        }
        
        public System.Threading.Tasks.Task<ViewComercio.ServiceReference1.Articles[]> ShowWSArticlesAsync() {
            return base.Channel.ShowWSArticlesAsync();
        }
    }
}
